[proxy]
proxy_server ansible_host=54.87.19.185

[agents]
build_agent ansible_host=54.87.230.239

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=./devops-key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
