---
- name: Configure Reverse Proxy
  hosts: proxy
  become: yes
  tasks:
    - name: Create Nginx configuration to point to Build Agent
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://54.242.126.175:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }

    - name: Restart Nginx to apply changes
      service:
        name: nginx
        state: restarted

