---
- name: Configure Nginx Proxy
  hosts: proxy
  become: yes  # This means "run as sudo"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
